<?php

// Data functions for table ads

// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

function ads_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('ads');
	if(!$arrPerm[1]){
		return false;
	}

	$data['advertiser'] = makeSafe($_POST['advertiser']);
		if($data['advertiser'] == empty_lookup_value){ $data['advertiser'] = ''; }
	$data['adName'] = makeSafe($_POST['adName']);
		if($data['adName'] == empty_lookup_value){ $data['adName'] = ''; }
	$data['code'] = makeSafe($_POST['code']);
		if($data['code'] == empty_lookup_value){ $data['code'] = ''; }
	$data['text'] = makeSafe($_POST['text']);
		if($data['text'] == empty_lookup_value){ $data['text'] = ''; }
	$data['active'] = makeSafe($_POST['active']);
		if($data['active'] == empty_lookup_value){ $data['active'] = ''; }
	$data['StartDate'] = intval($_POST['StartDateYear']) . '-' . intval($_POST['StartDateMonth']) . '-' . intval($_POST['StartDateDay']);
	$data['StartDate'] = parseMySQLDate($data['StartDate'], '');
	$data['EndDate'] = makeSafe($_POST['EndDate']);
		if($data['EndDate'] == empty_lookup_value){ $data['EndDate'] = ''; }
	$data['catagory'] = makeSafe($_POST['catagory']);
		if($data['catagory'] == empty_lookup_value){ $data['catagory'] = ''; }
	$data['image'] = PrepareUploadedFile('image', 1024000,'jpg|jpeg|gif|png', true, '');
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('ads', 'image', 'tv'));
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('ads', 'image', 'dv'));
	if($data['advertiser']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Advertiser': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['active']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Active': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: ads_before_insert
	if(function_exists('ads_before_insert')){
		$args=array();
		if(!ads_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `ads` set       `advertiser`=' . (($data['advertiser'] !== '' && $data['advertiser'] !== NULL) ? "'{$data['advertiser']}'" : 'NULL') . ', `adName`=' . (($data['adName'] !== '' && $data['adName'] !== NULL) ? "'{$data['adName']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')) . ', `code`=' . (($data['code'] !== '' && $data['code'] !== NULL) ? "'{$data['code']}'" : 'NULL') . ', `text`=' . (($data['text'] !== '' && $data['text'] !== NULL) ? "'{$data['text']}'" : 'NULL') . ', `active`=' . (($data['active'] !== '' && $data['active'] !== NULL) ? "'{$data['active']}'" : 'NULL') . ', `StartDate`=' . (($data['StartDate'] !== '' && $data['StartDate'] !== NULL) ? "'{$data['StartDate']}'" : 'NULL') . ', `EndDate`=' . (($data['EndDate'] !== '' && $data['EndDate'] !== NULL) ? "'{$data['EndDate']}'" : 'NULL') . ', `catagory`=' . (($data['catagory'] !== '' && $data['catagory'] !== NULL) ? "'{$data['catagory']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"ads_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: ads_after_insert
	if(function_exists('ads_after_insert')){
		$res = sql("select * from `ads` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!ads_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='ads', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function ads_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('ads');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ads' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ads' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: ads_before_delete
	if(function_exists('ads_before_delete')){
		$args=array();
		if(!ads_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `ads` where `id`='$selected_id'", $eo);

	// hook: ads_after_delete
	if(function_exists('ads_after_delete')){
		$args=array();
		ads_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='ads' and pkValue='$selected_id'", $eo);
}

function ads_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('ads');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ads' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ads' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['advertiser'] = makeSafe($_POST['advertiser']);
		if($data['advertiser'] == empty_lookup_value){ $data['advertiser'] = ''; }
	if($data['advertiser']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Advertiser': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['adName'] = makeSafe($_POST['adName']);
		if($data['adName'] == empty_lookup_value){ $data['adName'] = ''; }
	$data['code'] = makeSafe($_POST['code']);
		if($data['code'] == empty_lookup_value){ $data['code'] = ''; }
	$data['text'] = makeSafe($_POST['text']);
		if($data['text'] == empty_lookup_value){ $data['text'] = ''; }
	$data['active'] = makeSafe($_POST['active']);
		if($data['active'] == empty_lookup_value){ $data['active'] = ''; }
	if($data['active']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Active': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['StartDate'] = intval($_POST['StartDateYear']) . '-' . intval($_POST['StartDateMonth']) . '-' . intval($_POST['StartDateDay']);
	$data['StartDate'] = parseMySQLDate($data['StartDate'], '');
	$data['EndDate'] = makeSafe($_POST['EndDate']);
		if($data['EndDate'] == empty_lookup_value){ $data['EndDate'] = ''; }
	$data['catagory'] = makeSafe($_POST['catagory']);
		if($data['catagory'] == empty_lookup_value){ $data['catagory'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_POST['image_remove'] == 1){
		$data['image'] = '';
	}else{
		$data['image'] = PrepareUploadedFile('image', 1024000, 'jpg|jpeg|gif|png', true, "");
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('ads', 'image', 'tv'));
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('ads', 'image', 'dv'));
	}

	// hook: ads_before_update
	if(function_exists('ads_before_update')){
		$args=array();
		if(!ads_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `ads` set       `advertiser`=' . (($data['advertiser'] !== '' && $data['advertiser'] !== NULL) ? "'{$data['advertiser']}'" : 'NULL') . ', `adName`=' . (($data['adName'] !== '' && $data['adName'] !== NULL) ? "'{$data['adName']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')) . ', `code`=' . (($data['code'] !== '' && $data['code'] !== NULL) ? "'{$data['code']}'" : 'NULL') . ', `text`=' . (($data['text'] !== '' && $data['text'] !== NULL) ? "'{$data['text']}'" : 'NULL') . ', `active`=' . (($data['active'] !== '' && $data['active'] !== NULL) ? "'{$data['active']}'" : 'NULL') . ', `StartDate`=' . (($data['StartDate'] !== '' && $data['StartDate'] !== NULL) ? "'{$data['StartDate']}'" : 'NULL') . ', `EndDate`=' . (($data['EndDate'] !== '' && $data['EndDate'] !== NULL) ? "'{$data['EndDate']}'" : 'NULL') . ', `catagory`=' . (($data['catagory'] !== '' && $data['catagory'] !== NULL) ? "'{$data['catagory']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="ads_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: ads_after_update
	if(function_exists('ads_after_update')){
		$res = sql("SELECT * FROM `ads` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!ads_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='ads' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function ads_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('ads');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: StartDate
	$combo_StartDate = new DateCombo;
	$combo_StartDate->DateFormat = "mdy";
	$combo_StartDate->MinYear = 1900;
	$combo_StartDate->MaxYear = 2100;
	$combo_StartDate->DefaultDate = parseMySQLDate('', '');
	$combo_StartDate->MonthNames = $Translation['month names'];
	$combo_StartDate->NamePrefix = 'StartDate';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ads' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ads' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `ads` where `id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_StartDate->DefaultDate = $row['StartDate'];
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/ads_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/ads_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Ad details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return ads_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return ads_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return ads_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$arrPerm[1]) || (!$selected_id && !$arrPerm[1])){
		$jsReadOnly .= "\tjQuery('#advertiser').replaceWith('<p class=\"form-control-static\" id=\"advertiser\">' + (jQuery('#advertiser').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#adName').replaceWith('<p class=\"form-control-static\" id=\"adName\">' + (jQuery('#adName').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#image').replaceWith('<p class=\"form-control-static\" id=\"image\">' + (jQuery('#image').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#code').replaceWith('<p class=\"form-control-static\" id=\"code\">' + (jQuery('#code').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#text').replaceWith('<p class=\"form-control-static\" id=\"text\">' + (jQuery('#text').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#active').replaceWith('<p class=\"form-control-static\" id=\"active\">' + (jQuery('#active').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#StartDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#StartDateDay, #StartDateMonth, #StartDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#EndDate').replaceWith('<p class=\"form-control-static\" id=\"EndDate\">' + (jQuery('#EndDate').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#catagory').replaceWith('<p class=\"form-control-static\" id=\"catagory\">' + (jQuery('#catagory').val() || '') + '</p>');\n";

		$noUploads = true;
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(StartDate)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_StartDate->GetHTML(true) . '</p>' : $combo_StartDate->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(StartDate)%%>', $combo_StartDate->GetHTML(true), $templateCode);

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(advertiser)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(adName)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(image)%%>', ($noUploads ? '' : '<br /><input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input tabindex="1" type="file" name="image">'), $templateCode);
	if($AllowUpdate && $row['image']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '<br /><input tabindex="1" type="checkbox" name="image_remove" id="image_remove" value="1"> <label for="image_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(code)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(text)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(active)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(StartDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(EndDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(catagory)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(advertiser)%%>', htmlspecialchars($row['advertiser'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(advertiser)%%>', urlencode($urow['advertiser']), $templateCode);
		$templateCode=str_replace('<%%VALUE(adName)%%>', htmlspecialchars($row['adName'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(adName)%%>', urlencode($urow['adName']), $templateCode);
		$row['image']=($row['image']!=''?$row['image']:'');
		$templateCode=str_replace('<%%VALUE(image)%%>', htmlspecialchars($row['image'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image)%%>', urlencode($urow['image']), $templateCode);
		$templateCode=str_replace('<%%VALUE(code)%%>', htmlspecialchars($row['code'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(code)%%>', urlencode($urow['code']), $templateCode);
		$templateCode=str_replace('<%%VALUE(text)%%>', htmlspecialchars($row['text'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(text)%%>', urlencode($urow['text']), $templateCode);
		$templateCode=str_replace('<%%VALUE(active)%%>', htmlspecialchars($row['active'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(active)%%>', urlencode($urow['active']), $templateCode);
		$templateCode=str_replace('<%%VALUE(StartDate)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['StartDate'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(StartDate)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['StartDate'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(EndDate)%%>', htmlspecialchars($row['EndDate'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EndDate)%%>', urlencode($urow['EndDate']), $templateCode);
		$templateCode=str_replace('<%%VALUE(catagory)%%>', htmlspecialchars($row['catagory'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(catagory)%%>', urlencode($urow['catagory']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(advertiser)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(advertiser)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(adName)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(adName)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(image)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(code)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(code)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(text)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(text)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(active)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(active)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(StartDate)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(StartDate)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(EndDate)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EndDate)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(catagory)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(catagory)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: ads_dv
	if(function_exists('ads_dv')){
		$args=array();
		ads_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>