<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/ads.php");
	include("$currDir/ads_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('ads');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "ads";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`ads`.`id`" => "id",
		"`ads`.`advertiser`" => "advertiser",
		"`ads`.`adName`" => "adName",
		"`ads`.`image`" => "image",
		"`ads`.`code`" => "code",
		"`ads`.`text`" => "text",
		"`ads`.`active`" => "active",
		"if(`ads`.`StartDate`,date_format(`ads`.`StartDate`,'%m/%d/%Y'),'')" => "StartDate",
		"`ads`.`EndDate`" => "EndDate",
		"`ads`.`catagory`" => "catagory"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`ads`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`ads`.`StartDate`',
		9 => 9,
		10 => '`ads`.`catagory`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`ads`.`id`" => "id",
		"`ads`.`advertiser`" => "advertiser",
		"`ads`.`adName`" => "adName",
		"`ads`.`image`" => "image",
		"`ads`.`code`" => "code",
		"`ads`.`text`" => "text",
		"`ads`.`active`" => "active",
		"if(`ads`.`StartDate`,date_format(`ads`.`StartDate`,'%m/%d/%Y'),'')" => "StartDate",
		"`ads`.`EndDate`" => "EndDate",
		"`ads`.`catagory`" => "catagory"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`ads`.`id`" => "ID",
		"`ads`.`advertiser`" => "Advertiser",
		"`ads`.`adName`" => "AdName",
		"`ads`.`code`" => "Code",
		"`ads`.`text`" => "Text",
		"`ads`.`active`" => "Active",
		"`ads`.`StartDate`" => "StartDate",
		"`ads`.`EndDate`" => "EndDate",
		"`ads`.`catagory`" => "ShownOn"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`ads`.`id`" => "id",
		"`ads`.`advertiser`" => "advertiser",
		"`ads`.`adName`" => "adName",
		"`ads`.`code`" => "code",
		"`ads`.`text`" => "text",
		"`ads`.`active`" => "active",
		"if(`ads`.`StartDate`,date_format(`ads`.`StartDate`,'%m/%d/%Y'),'')" => "StartDate",
		"`ads`.`EndDate`" => "EndDate",
		"`ads`.`catagory`" => "catagory"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`ads` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "ads_view.php";
	$x->RedirectAfterInsert = "ads_view.php?SelectedID=#ID#";
	$x->TableTitle = "Ads";
	$x->TableIcon = "resources/table_icons/align_right.png";
	$x->PrimaryKey = "`ads`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Advertiser", "AdName", "Image", "Code", "Text", "Active", "StartDate", "EndDate", "ShownOn");
	$x->ColFieldName = array('advertiser', 'adName', 'image', 'code', 'text', 'active', 'StartDate', 'EndDate', 'catagory');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	$x->Template = 'templates/ads_templateTV.html';
	$x->SelectedTemplate = 'templates/ads_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='ads' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='ads' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`ads`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: ads_init
	$render=TRUE;
	if(function_exists('ads_init')){
		$args=array();
		$render=ads_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: ads_header
	$headerCode='';
	if(function_exists('ads_header')){
		$args=array();
		$headerCode=ads_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: ads_footer
	$footerCode='';
	if(function_exists('ads_footer')){
		$args=array();
		$footerCode=ads_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>