<?php

// Data functions for table advertisers

// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

function advertisers_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('advertisers');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Name'] = makeSafe($_POST['Name']);
		if($data['Name'] == empty_lookup_value){ $data['Name'] = ''; }
	$data['AffilateCode'] = makeSafe($_POST['AffilateCode']);
		if($data['AffilateCode'] == empty_lookup_value){ $data['AffilateCode'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['Contact'] = makeSafe($_POST['Contact']);
		if($data['Contact'] == empty_lookup_value){ $data['Contact'] = ''; }
	$data['email'] = makeSafe($_POST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }

	// hook: advertisers_before_insert
	if(function_exists('advertisers_before_insert')){
		$args=array();
		if(!advertisers_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `advertisers` set       `Name`=' . (($data['Name'] !== '' && $data['Name'] !== NULL) ? "'{$data['Name']}'" : 'NULL') . ', `AffilateCode`=' . (($data['AffilateCode'] !== '' && $data['AffilateCode'] !== NULL) ? "'{$data['AffilateCode']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `Contact`=' . (($data['Contact'] !== '' && $data['Contact'] !== NULL) ? "'{$data['Contact']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"advertisers_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: advertisers_after_insert
	if(function_exists('advertisers_after_insert')){
		$res = sql("select * from `advertisers` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!advertisers_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='advertisers', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function advertisers_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('advertisers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertisers' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='advertisers' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: advertisers_before_delete
	if(function_exists('advertisers_before_delete')){
		$args=array();
		if(!advertisers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `advertisers` where `id`='$selected_id'", $eo);

	// hook: advertisers_after_delete
	if(function_exists('advertisers_after_delete')){
		$args=array();
		advertisers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='advertisers' and pkValue='$selected_id'", $eo);
}

function advertisers_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('advertisers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertisers' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='advertisers' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Name'] = makeSafe($_POST['Name']);
		if($data['Name'] == empty_lookup_value){ $data['Name'] = ''; }
	$data['AffilateCode'] = makeSafe($_POST['AffilateCode']);
		if($data['AffilateCode'] == empty_lookup_value){ $data['AffilateCode'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['Contact'] = makeSafe($_POST['Contact']);
		if($data['Contact'] == empty_lookup_value){ $data['Contact'] = ''; }
	$data['email'] = makeSafe($_POST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: advertisers_before_update
	if(function_exists('advertisers_before_update')){
		$args=array();
		if(!advertisers_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `advertisers` set       `Name`=' . (($data['Name'] !== '' && $data['Name'] !== NULL) ? "'{$data['Name']}'" : 'NULL') . ', `AffilateCode`=' . (($data['AffilateCode'] !== '' && $data['AffilateCode'] !== NULL) ? "'{$data['AffilateCode']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `Contact`=' . (($data['Contact'] !== '' && $data['Contact'] !== NULL) ? "'{$data['Contact']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="advertisers_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: advertisers_after_update
	if(function_exists('advertisers_after_update')){
		$res = sql("SELECT * FROM `advertisers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!advertisers_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='advertisers' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function advertisers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('advertisers');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='advertisers' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='advertisers' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `advertisers` where `id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/advertisers_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/advertisers_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Advertiser details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return advertisers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return advertisers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return advertisers_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$arrPerm[1]) || (!$selected_id && !$arrPerm[1])){
		$jsReadOnly .= "\tjQuery('#Name').replaceWith('<p class=\"form-control-static\" id=\"Name\">' + (jQuery('#Name').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#AffilateCode').replaceWith('<p class=\"form-control-static\" id=\"AffilateCode\">' + (jQuery('#AffilateCode').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#URL').replaceWith('<p class=\"form-control-static\" id=\"URL\">' + (jQuery('#URL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Contact').replaceWith('<p class=\"form-control-static\" id=\"Contact\">' + (jQuery('#Contact').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<p class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#email, #email-edit-link').hide();\n";

		$noUploads = true;
	}

	// process combos

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(AffilateCode)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(URL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Contact)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Name)%%>', htmlspecialchars($row['Name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Name)%%>', urlencode($urow['Name']), $templateCode);
		$templateCode=str_replace('<%%VALUE(AffilateCode)%%>', htmlspecialchars($row['AffilateCode'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AffilateCode)%%>', urlencode($urow['AffilateCode']), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', htmlspecialchars($row['URL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode($urow['URL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Contact)%%>', htmlspecialchars($row['Contact'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Contact)%%>', urlencode($urow['Contact']), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', htmlspecialchars($row['email'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Name)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(AffilateCode)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AffilateCode)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Contact)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Contact)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: advertisers_dv
	if(function_exists('advertisers_dv')){
		$args=array();
		advertisers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>