<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/advertisers.php");
	include("$currDir/advertisers_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('advertisers');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "advertisers";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`advertisers`.`id`" => "id",
		"`advertisers`.`Name`" => "Name",
		"`advertisers`.`AffilateCode`" => "AffilateCode",
		"`advertisers`.`URL`" => "URL",
		"`advertisers`.`Contact`" => "Contact",
		"`advertisers`.`email`" => "email"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`advertisers`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`advertisers`.`id`" => "id",
		"`advertisers`.`Name`" => "Name",
		"`advertisers`.`AffilateCode`" => "AffilateCode",
		"`advertisers`.`URL`" => "URL",
		"`advertisers`.`Contact`" => "Contact",
		"`advertisers`.`email`" => "email"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`advertisers`.`id`" => "ID",
		"`advertisers`.`Name`" => "Name",
		"`advertisers`.`AffilateCode`" => "AffilateCode",
		"`advertisers`.`URL`" => "URL",
		"`advertisers`.`Contact`" => "Contact",
		"`advertisers`.`email`" => "Email"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`advertisers`.`id`" => "id",
		"`advertisers`.`Name`" => "Name",
		"`advertisers`.`AffilateCode`" => "AffilateCode",
		"`advertisers`.`URL`" => "URL",
		"`advertisers`.`Contact`" => "Contact",
		"`advertisers`.`email`" => "email"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`advertisers` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "advertisers_view.php";
	$x->RedirectAfterInsert = "advertisers_view.php?SelectedID=#ID#";
	$x->TableTitle = "Advertisers";
	$x->TableIcon = "resources/table_icons/book_addresses.png";
	$x->PrimaryKey = "`advertisers`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Name", "AffilateCode", "URL", "Contact", "Email");
	$x->ColFieldName = array('Name', 'AffilateCode', 'URL', 'Contact', 'email');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	$x->Template = 'templates/advertisers_templateTV.html';
	$x->SelectedTemplate = 'templates/advertisers_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `advertisers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='advertisers' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `advertisers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='advertisers' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`advertisers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: advertisers_init
	$render=TRUE;
	if(function_exists('advertisers_init')){
		$args=array();
		$render=advertisers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: advertisers_header
	$headerCode='';
	if(function_exists('advertisers_header')){
		$args=array();
		$headerCode=advertisers_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: advertisers_footer
	$footerCode='';
	if(function_exists('advertisers_footer')){
		$args=array();
		$footerCode=advertisers_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>