<?php

// Data functions for table media

// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

function media_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('media');
	if(!$arrPerm[1]){
		return false;
	}

	$data['type'] = makeSafe($_POST['type']);
		if($data['type'] == empty_lookup_value){ $data['type'] = ''; }
	$data['title'] = makeSafe($_POST['title']);
		if($data['title'] == empty_lookup_value){ $data['title'] = ''; }
	$data['artist'] = makeSafe($_POST['artist']);
		if($data['artist'] == empty_lookup_value){ $data['artist'] = ''; }
	$data['condition'] = makeSafe($_POST['condition']);
		if($data['condition'] == empty_lookup_value){ $data['condition'] = ''; }
	$data['price'] = makeSafe($_POST['price']);
		if($data['price'] == empty_lookup_value){ $data['price'] = ''; }
	$data['active'] = makeSafe($_POST['active']);
		if($data['active'] == empty_lookup_value){ $data['active'] = ''; }
	$data['description'] = makeSafe($_POST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['buttoncode'] = makeSafe($_POST['buttoncode']);
		if($data['buttoncode'] == empty_lookup_value){ $data['buttoncode'] = ''; }
	$data['buttonactive'] = makeSafe($_POST['buttonactive']);
		if($data['buttonactive'] == empty_lookup_value){ $data['buttonactive'] = ''; }
	$data['owner'] = parseCode('<%%creatorUsername%%>', true);
	$data['ip'] = parseCode('<%%creatorIP%%>', true);
	$data['date'] = parseCode('<%%creationDate%%>', true, true);
	$data['image'] = PrepareUploadedFile('image', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('media', 'image', 'tv'));
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('media', 'image', 'dv'));
	$data['image2'] = PrepareUploadedFile('image2', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image2']) createThumbnail($data['image2'], getThumbnailSpecs('media', 'image2', 'tv'));
	if($data['image2']) createThumbnail($data['image2'], getThumbnailSpecs('media', 'image2', 'dv'));
	if($data['type']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Type': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['title']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Title': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['artist']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Artist': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['condition']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Condition': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['price'] == '') $data['price'] = "0.00";
	if($data['price']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Price': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['active'] == '') $data['active'] = "1";
	if($data['active']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Active': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['description']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Description': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['buttonactive'] == '') $data['buttonactive'] = "1";

	// hook: media_before_insert
	if(function_exists('media_before_insert')){
		$args=array();
		if(!media_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `media` set       `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL') . ', `title`=' . (($data['title'] !== '' && $data['title'] !== NULL) ? "'{$data['title']}'" : 'NULL') . ', `artist`=' . (($data['artist'] !== '' && $data['artist'] !== NULL) ? "'{$data['artist']}'" : 'NULL') . ', `condition`=' . (($data['condition'] !== '' && $data['condition'] !== NULL) ? "'{$data['condition']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')) . ', ' . ($data['image2']!='' ? "`image2`='{$data['image2']}'" : ($_POST['image2_remove'] != 1 ? '`image2`=`image2`' : '`image2`=NULL')) . ', `price`=' . (($data['price'] !== '' && $data['price'] !== NULL) ? "'{$data['price']}'" : 'NULL') . ', `active`=' . (($data['active'] !== '' && $data['active'] !== NULL) ? "'{$data['active']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `buttoncode`=' . (($data['buttoncode'] !== '' && $data['buttoncode'] !== NULL) ? "'{$data['buttoncode']}'" : 'NULL') . ', `buttonactive`=' . (($data['buttonactive'] !== '' && $data['buttonactive'] !== NULL) ? "'{$data['buttonactive']}'" : 'NULL') . ', `owner`=' . "'{$data['owner']}'" . ', `ip`=' . "'{$data['ip']}'" . ', `date`=' . "'{$data['date']}'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"media_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: media_after_insert
	if(function_exists('media_after_insert')){
		$res = sql("select * from `media` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!media_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='media', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function media_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('media');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='media' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='media' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: media_before_delete
	if(function_exists('media_before_delete')){
		$args=array();
		if(!media_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// delete file stored in the 'image2' field
	$res = sql("select `image2` from `media` where `id`='$selected_id'", $eo);
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir('').$row[0]);
			preg_match('/^[a-z0-9_]+\.(gif|png|jpg|jpeg|jpe)$/i', $row[0], $m);
			$thumbDV=str_replace(".$m[1]ffffgggg", "_dv.$m[1]", $row[0].'ffffgggg');
			$thumbTV=str_replace(".$m[1]ffffgggg", "_tv.$m[1]", $row[0].'ffffgggg');
			@unlink(getUploadDir('').$thumbTV);
			@unlink(getUploadDir('').$thumbDV);
		}
	}

	sql("delete from `media` where `id`='$selected_id'", $eo);

	// hook: media_after_delete
	if(function_exists('media_after_delete')){
		$args=array();
		media_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='media' and pkValue='$selected_id'", $eo);
}

function media_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('media');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='media' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='media' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['type'] = makeSafe($_POST['type']);
		if($data['type'] == empty_lookup_value){ $data['type'] = ''; }
	if($data['type']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Type': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['title'] = makeSafe($_POST['title']);
		if($data['title'] == empty_lookup_value){ $data['title'] = ''; }
	if($data['title']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Title': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['artist'] = makeSafe($_POST['artist']);
		if($data['artist'] == empty_lookup_value){ $data['artist'] = ''; }
	if($data['artist']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Artist': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['condition'] = makeSafe($_POST['condition']);
		if($data['condition'] == empty_lookup_value){ $data['condition'] = ''; }
	if($data['condition']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Condition': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['price'] = makeSafe($_POST['price']);
		if($data['price'] == empty_lookup_value){ $data['price'] = ''; }
	if($data['price']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Price': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['active'] = makeSafe($_POST['active']);
		if($data['active'] == empty_lookup_value){ $data['active'] = ''; }
	if($data['active']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Active': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['description'] = makeSafe($_POST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	if($data['description']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Description': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['buttoncode'] = makeSafe($_POST['buttoncode']);
		if($data['buttoncode'] == empty_lookup_value){ $data['buttoncode'] = ''; }
	$data['buttonactive'] = makeSafe($_POST['buttonactive']);
		if($data['buttonactive'] == empty_lookup_value){ $data['buttonactive'] = ''; }
	$data['date'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['selectedID']=makeSafe($selected_id);
	if($_POST['image_remove'] == 1){
		$data['image'] = '';
	}else{
		$data['image'] = PrepareUploadedFile('image', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('media', 'image', 'tv'));
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('media', 'image', 'dv'));
	}
	if($_POST['image2_remove'] == 1){
		$data['image2'] = '';
		// delete file from server
		$res = sql("select `image2` from `media` where `id`='".makeSafe($selected_id)."'", $eo);
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir('').$row[0]);
				preg_match('/^[a-z0-9_]+\.(gif|png|jpg|jpeg|jpe)$/i', $row[0], $m);
				$thumbDV=str_replace(".$m[1]ffffgggg", "_dv.$m[1]", $row[0].'ffffgggg');
				$thumbTV=str_replace(".$m[1]ffffgggg", "_tv.$m[1]", $row[0].'ffffgggg');
				@unlink(getUploadDir('').$thumbTV);
				@unlink(getUploadDir('').$thumbDV);
			}
		}
	}else{
		$data['image2'] = PrepareUploadedFile('image2', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image2']) createThumbnail($data['image2'], getThumbnailSpecs('media', 'image2', 'tv'));
		if($data['image2']) createThumbnail($data['image2'], getThumbnailSpecs('media', 'image2', 'dv'));
		// delete file from server
		if($data['image2'] != ''){
			$res = sql("select `image2` from `media` where `id`='".makeSafe($selected_id)."'", $eo);
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir('').$row[0]);
					preg_match('/^[a-z0-9_]+\.(gif|png|jpg|jpeg|jpe)$/i', $row[0], $m);
					$thumbDV=str_replace(".$m[1]ffffgggg", "_dv.$m[1]", $row[0].'ffffgggg');
					$thumbTV=str_replace(".$m[1]ffffgggg", "_tv.$m[1]", $row[0].'ffffgggg');
					@unlink(getUploadDir('').$thumbTV);
					@unlink(getUploadDir('').$thumbDV);
				}
			}
		}
	}

	// hook: media_before_update
	if(function_exists('media_before_update')){
		$args=array();
		if(!media_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `media` set       `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL') . ', `title`=' . (($data['title'] !== '' && $data['title'] !== NULL) ? "'{$data['title']}'" : 'NULL') . ', `artist`=' . (($data['artist'] !== '' && $data['artist'] !== NULL) ? "'{$data['artist']}'" : 'NULL') . ', `condition`=' . (($data['condition'] !== '' && $data['condition'] !== NULL) ? "'{$data['condition']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')) . ', ' . ($data['image2']!='' ? "`image2`='{$data['image2']}'" : ($_POST['image2_remove'] != 1 ? '`image2`=`image2`' : '`image2`=NULL')) . ', `price`=' . (($data['price'] !== '' && $data['price'] !== NULL) ? "'{$data['price']}'" : 'NULL') . ', `active`=' . (($data['active'] !== '' && $data['active'] !== NULL) ? "'{$data['active']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `buttoncode`=' . (($data['buttoncode'] !== '' && $data['buttoncode'] !== NULL) ? "'{$data['buttoncode']}'" : 'NULL') . ', `buttonactive`=' . (($data['buttonactive'] !== '' && $data['buttonactive'] !== NULL) ? "'{$data['buttonactive']}'" : 'NULL') . ', `date`=' . (($data['date'] != '') ? "'{$data['date']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="media_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: media_after_update
	if(function_exists('media_after_update')){
		$res = sql("SELECT * FROM `media` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!media_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='media' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function media_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('media');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: type
	$combo_type = new Combo;
	$combo_type->ListType = 0;
	$combo_type->MultipleSeparator = ', ';
	$combo_type->ListBoxHeight = 10;
	$combo_type->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/media.type.csv')){
		$type_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/media.type.csv')));
		$combo_type->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($type_data)));
		$combo_type->ListData = $combo_type->ListItem;
	}else{
		$combo_type->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("cd;;dvd;;vhs;;bluray;;cassette;;ps1;;ps2;;ps3;;ps4;;xbox;;xbox360;;xboxone;;wii;;other;;book;;poster;;iphone;;android;;tablet;;digital")));
		$combo_type->ListData = $combo_type->ListItem;
	}
	$combo_type->SelectName = 'type';
	$combo_type->AllowNull = false;
	// combobox: condition
	$combo_condition = new Combo;
	$combo_condition->ListType = 0;
	$combo_condition->MultipleSeparator = ', ';
	$combo_condition->ListBoxHeight = 10;
	$combo_condition->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/media.condition.csv')){
		$condition_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/media.condition.csv')));
		$combo_condition->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($condition_data)));
		$combo_condition->ListData = $combo_condition->ListItem;
	}else{
		$combo_condition->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("new;;used;;worn;;working;;for parts;;not working;;unboxed;;")));
		$combo_condition->ListData = $combo_condition->ListItem;
	}
	$combo_condition->SelectName = 'condition';
	$combo_condition->AllowNull = false;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='media' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='media' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `media` where `id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_type->SelectedData = $row['type'];
		$combo_condition->SelectedData = $row['condition'];
		$combo_date->DefaultDate = $row['date'];
	}else{
		$combo_type->SelectedText = ( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_condition->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_type->Render();
	$combo_condition->Render();

	// code for template based detail view forms

	// open the detail view template
	$templateCode = @file_get_contents('./templates/media_templateDV.html');

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Media details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return media_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return media_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return media_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$arrPerm[1]) || (!$selected_id && !$arrPerm[1])){
		$jsReadOnly .= "\tjQuery('#type').replaceWith('<p class=\"form-control-static\" id=\"type\">' + (jQuery('#type').val() || '') + '</p>'); jQuery('#type-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#title').replaceWith('<p class=\"form-control-static\" id=\"title\">' + (jQuery('#title').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#artist').replaceWith('<p class=\"form-control-static\" id=\"artist\">' + (jQuery('#artist').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#condition').replaceWith('<p class=\"form-control-static\" id=\"condition\">' + (jQuery('#condition').val() || '') + '</p>'); jQuery('#condition-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#image').replaceWith('<p class=\"form-control-static\" id=\"image\">' + (jQuery('#image').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#image2').replaceWith('<p class=\"form-control-static\" id=\"image2\">' + (jQuery('#image2').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#price').replaceWith('<p class=\"form-control-static\" id=\"price\">' + (jQuery('#price').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#active').replaceWith('<p class=\"form-control-static\" id=\"active\">' + (jQuery('#active').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#buttoncode').replaceWith('<p class=\"form-control-static\" id=\"buttoncode\">' + (jQuery('#buttoncode').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#buttonactive').replaceWith('<p class=\"form-control-static\" id=\"buttonactive\">' + (jQuery('#buttonactive').val() || '') + '</p>');\n";

		$noUploads = true;
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(type)%%>', $combo_type->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(type)%%>', $combo_type->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(condition)%%>', $combo_condition->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(condition)%%>', $combo_condition->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_date->GetHTML(true) . '</p>' : $combo_date->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(title)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(artist)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(condition)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(image)%%>', ($noUploads ? '' : '<br /><input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input tabindex="1" type="file" name="image">'), $templateCode);
	if($AllowUpdate && $row['image']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '<br /><input tabindex="1" type="checkbox" name="image_remove" id="image_remove" value="1"> <label for="image_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(image2)%%>', ($noUploads ? '' : '<br /><input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input tabindex="1" type="file" name="image2">'), $templateCode);
	if($AllowUpdate && $row['image2']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image2)%%>', '<br /><input tabindex="1" type="checkbox" name="image2_remove" id="image2_remove" value="1"> <label for="image2_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image2)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(price)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(active)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(buttoncode)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(buttonactive)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(owner)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(type)%%>', htmlspecialchars($row['type'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
		$templateCode=str_replace('<%%VALUE(title)%%>', htmlspecialchars($row['title'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(title)%%>', urlencode($urow['title']), $templateCode);
		$templateCode=str_replace('<%%VALUE(artist)%%>', htmlspecialchars($row['artist'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(artist)%%>', urlencode($urow['artist']), $templateCode);
		$templateCode=str_replace('<%%VALUE(condition)%%>', htmlspecialchars($row['condition'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(condition)%%>', urlencode($urow['condition']), $templateCode);
		$row['image']=($row['image']!=''?$row['image']:'');
		$templateCode=str_replace('<%%VALUE(image)%%>', htmlspecialchars($row['image'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image)%%>', urlencode($urow['image']), $templateCode);
		$row['image2']=($row['image2']!=''?$row['image2']:'');
		$templateCode=str_replace('<%%VALUE(image2)%%>', htmlspecialchars($row['image2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image2)%%>', urlencode($urow['image2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(price)%%>', htmlspecialchars($row['price'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(price)%%>', urlencode($urow['price']), $templateCode);
		$templateCode=str_replace('<%%VALUE(active)%%>', htmlspecialchars($row['active'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(active)%%>', urlencode($urow['active']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode=str_replace('<%%HTMLAREA(description)%%>', '<textarea tabindex="1" name="description" id="description" rows="5">'.htmlspecialchars($row['description'], ENT_QUOTES).'</textarea>', $templateCode);
		}else{
			$templateCode=str_replace('<%%HTMLAREA(description)%%>', $row['description'], $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(description)%%>', nl2br($row['description']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		$templateCode=str_replace('<%%VALUE(buttoncode)%%>', htmlspecialchars($row['buttoncode'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(buttoncode)%%>', urlencode($urow['buttoncode']), $templateCode);
		$templateCode=str_replace('<%%VALUE(buttonactive)%%>', htmlspecialchars($row['buttonactive'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(buttonactive)%%>', urlencode($urow['buttonactive']), $templateCode);
		$templateCode=str_replace('<%%VALUE(owner)%%>', htmlspecialchars($row['owner'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(owner)%%>', urlencode($urow['owner']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ip)%%>', htmlspecialchars($row['ip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ip)%%>', urlencode($urow['ip']), $templateCode);
		$templateCode=str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['date'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['date'], ENT_QUOTES)))), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(type)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(title)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(title)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(artist)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(artist)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(condition)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(condition)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(image)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(image2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(price)%%>', '0.00', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(price)%%>', urlencode('0.00'), $templateCode);
		$templateCode=str_replace('<%%VALUE(active)%%>', '1', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(active)%%>', urlencode('1'), $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(description)%%>', '<textarea tabindex="1" name="description" id="description" rows="5"></textarea>', $templateCode);
		$templateCode=str_replace('<%%VALUE(buttoncode)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(buttoncode)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(buttonactive)%%>', '1', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(buttonactive)%%>', urlencode('1'), $templateCode);
		$templateCode=str_replace('<%%VALUE(owner)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(owner)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(ip)%%>', '<%%creatorIP%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ip)%%>', urlencode('<%%creatorIP%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: media_dv
	if(function_exists('media_dv')){
		$args=array();
		media_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>