<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/media.php");
	include("$currDir/media_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('media');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "media";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`media`.`id`" => "id",
		"if(CHAR_LENGTH(`media`.`type`)>10, concat(left(`media`.`type`,10),' ...'), `media`.`type`)" => "type",
		"`media`.`title`" => "title",
		"`media`.`artist`" => "artist",
		"`media`.`condition`" => "condition",
		"`media`.`image`" => "image",
		"`media`.`image2`" => "image2",
		"`media`.`price`" => "price",
		"`media`.`active`" => "active",
		"`media`.`description`" => "description",
		"`media`.`buttoncode`" => "buttoncode",
		"`media`.`buttonactive`" => "buttonactive",
		"`media`.`owner`" => "owner",
		"`media`.`ip`" => "ip",
		"if(`media`.`date`,date_format(`media`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`media`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`media`.`price`',
		9 => '`media`.`active`',
		10 => 10,
		11 => 11,
		12 => '`media`.`buttonactive`',
		13 => 13,
		14 => 14,
		15 => '`media`.`date`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`media`.`id`" => "id",
		"`media`.`type`" => "type",
		"`media`.`title`" => "title",
		"`media`.`artist`" => "artist",
		"`media`.`condition`" => "condition",
		"`media`.`image`" => "image",
		"`media`.`image2`" => "image2",
		"`media`.`price`" => "price",
		"`media`.`active`" => "active",
		"`media`.`description`" => "description",
		"`media`.`buttoncode`" => "buttoncode",
		"`media`.`buttonactive`" => "buttonactive",
		"`media`.`owner`" => "owner",
		"`media`.`ip`" => "ip",
		"if(`media`.`date`,date_format(`media`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`media`.`id`" => "ID",
		"`media`.`type`" => "Type",
		"`media`.`title`" => "Title",
		"`media`.`artist`" => "Artist",
		"`media`.`condition`" => "Condition",
		"`media`.`price`" => "Price",
		"`media`.`active`" => "Active",
		"`media`.`description`" => "Description",
		"`media`.`buttoncode`" => "Buttoncode",
		"`media`.`buttonactive`" => "Buttonactive",
		"`media`.`owner`" => "Owner",
		"`media`.`ip`" => "Ip",
		"`media`.`date`" => "Date"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`media`.`id`" => "id",
		"`media`.`type`" => "Type",
		"`media`.`title`" => "title",
		"`media`.`artist`" => "artist",
		"`media`.`condition`" => "condition",
		"`media`.`price`" => "price",
		"`media`.`active`" => "active",
		"`media`.`description`" => "description",
		"`media`.`buttoncode`" => "buttoncode",
		"`media`.`buttonactive`" => "Buttonactive",
		"`media`.`owner`" => "owner",
		"`media`.`ip`" => "ip",
		"if(`media`.`date`,date_format(`media`.`date`,'%m/%d/%Y'),'')" => "date"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`media` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "media_view.php";
	$x->RedirectAfterInsert = "media_view.php?SelectedID=#ID#";
	$x->TableTitle = "Media";
	$x->TableIcon = "resources/table_icons/backup_manager.png";
	$x->PrimaryKey = "`media`.`id`";
	$x->DefaultSortField = '`media`.`date`';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 80, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Type", "Title", "Artist", "Condition", "Image", "Image2", "Price", "Active", "Description", "Buttoncode", "Buttonactive", "Date");
	$x->ColFieldName = array('type', 'title', 'artist', 'condition', 'image', 'image2', 'price', 'active', 'description', 'buttoncode', 'buttonactive', 'date');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15);

	$x->Template = 'templates/media_templateTV.html';
	$x->SelectedTemplate = 'templates/media_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `media`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='media' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `media`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='media' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`media`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: media_init
	$render=TRUE;
	if(function_exists('media_init')){
		$args=array();
		$render=media_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: media_header
	$headerCode='';
	if(function_exists('media_header')){
		$args=array();
		$headerCode=media_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: media_footer
	$footerCode='';
	if(function_exists('media_footer')){
		$args=array();
		$footerCode=media_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>