<?php

// Data functions for table owners

// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

function owners_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('owners');
	if(!$arrPerm[1]){
		return false;
	}

	$data['pass'] = makeSafe($_POST['pass']);
		if($data['pass'] == empty_lookup_value){ $data['pass'] = ''; }
	$data['level'] = makeSafe($_POST['level']);
		if($data['level'] == empty_lookup_value){ $data['level'] = ''; }
	$data['image'] = PrepareUploadedFile('image', 102400,'jpg|jpeg|gif|png', false, '');
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('owners', 'image', 'tv'));
	if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('owners', 'image', 'dv'));
	if($data['level'] == '') $data['level'] = "1";

	// hook: owners_before_insert
	if(function_exists('owners_before_insert')){
		$args=array();
		if(!owners_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `owners` set       `pass`=' . (($data['pass'] !== '' && $data['pass'] !== NULL) ? "'{$data['pass']}'" : 'NULL') . ', `level`=' . (($data['level'] !== '' && $data['level'] !== NULL) ? "'{$data['level']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"owners_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: owners_after_insert
	if(function_exists('owners_after_insert')){
		$res = sql("select * from `owners` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!owners_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='owners', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function owners_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('owners');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='owners' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='owners' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: owners_before_delete
	if(function_exists('owners_before_delete')){
		$args=array();
		if(!owners_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `owners` where `id`='$selected_id'", $eo);

	// hook: owners_after_delete
	if(function_exists('owners_after_delete')){
		$args=array();
		owners_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='owners' and pkValue='$selected_id'", $eo);
}

function owners_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('owners');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='owners' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='owners' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['pass'] = makeSafe($_POST['pass']);
		if($data['pass'] == empty_lookup_value){ $data['pass'] = ''; }
	$data['level'] = makeSafe($_POST['level']);
		if($data['level'] == empty_lookup_value){ $data['level'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_POST['image_remove'] == 1){
		$data['image'] = '';
	}else{
		$data['image'] = PrepareUploadedFile('image', 102400, 'jpg|jpeg|gif|png', false, "");
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('owners', 'image', 'tv'));
		if($data['image']) createThumbnail($data['image'], getThumbnailSpecs('owners', 'image', 'dv'));
	}

	// hook: owners_before_update
	if(function_exists('owners_before_update')){
		$args=array();
		if(!owners_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `owners` set       `pass`=' . (($data['pass'] !== '' && $data['pass'] !== NULL) ? "'{$data['pass']}'" : 'NULL') . ', `level`=' . (($data['level'] !== '' && $data['level'] !== NULL) ? "'{$data['level']}'" : 'NULL') . ', ' . ($data['image']!='' ? "`image`='{$data['image']}'" : ($_POST['image_remove'] != 1 ? '`image`=`image`' : '`image`=NULL')) . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="owners_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: owners_after_update
	if(function_exists('owners_after_update')){
		$res = sql("SELECT * FROM `owners` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!owners_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='owners' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function owners_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('owners');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='owners' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='owners' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `owners` where `id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/owners_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/owners_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Owner details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return owners_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return owners_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return owners_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$arrPerm[1]) || (!$selected_id && !$arrPerm[1])){
		$jsReadOnly .= "\tjQuery('#pass').replaceWith('<p class=\"form-control-static\" id=\"pass\">' + (jQuery('#pass').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#level').replaceWith('<p class=\"form-control-static\" id=\"level\">' + (jQuery('#level').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#image').replaceWith('<p class=\"form-control-static\" id=\"image\">' + (jQuery('#image').val() || '') + '</p>');\n";

		$noUploads = true;
	}

	// process combos

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(pass)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(level)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(image)%%>', ($noUploads ? '' : '<br /><input type=hidden name=MAX_FILE_SIZE value=102400>'.$Translation['upload image'].' <input tabindex="1" type="file" name="image">'), $templateCode);
	if($AllowUpdate && $row['image']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '<br /><input tabindex="1" type="checkbox" name="image_remove" id="image_remove" value="1"> <label for="image_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image)%%>', '', $templateCode);
	}

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(name)%%>', htmlspecialchars($row['name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		$templateCode=str_replace('<%%VALUE(pass)%%>', htmlspecialchars($row['pass'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(pass)%%>', urlencode($urow['pass']), $templateCode);
		$templateCode=str_replace('<%%VALUE(level)%%>', htmlspecialchars($row['level'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(level)%%>', urlencode($urow['level']), $templateCode);
		$row['image']=($row['image']!=''?$row['image']:'');
		$templateCode=str_replace('<%%VALUE(image)%%>', htmlspecialchars($row['image'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image)%%>', urlencode($urow['image']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(pass)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(pass)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(level)%%>', '1', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(level)%%>', urlencode('1'), $templateCode);
		$templateCode=str_replace('<%%VALUE(image)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: owners_dv
	if(function_exists('owners_dv')){
		$args=array();
		owners_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>